### ISSUE TITLE
Adaptivity

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-yarn#1]
So how do we handle adaptive loads?  There are a few actors here living in different places here:

1.  The dask client, which infrequently changes some parameters to the adaptivity (like maximum number of workers) 
2.  The skein client, which somewhat frequently needs to add or destroy workers
3.  The scheduler which changes state very frequently
4.  The adaptive object, which looks at some of the scheduler state and decides to ask the skein client (or other object satisfying the Cluster interface) to scale up or down appropriately.

So it's convenient if the Adaptive and Scheduler objects are in the same thread.  The Dask Client and the Scheduler are likely on different machines.  Should the Skein Client be with the Dask Client or the Scheduler?

### Skein Client with Dask Client

If the Skein Cleint should be with the Dask Client then we should probably make a RemoteCluster object that lives with the Scheduler, but just streams back signals to us.

```python
class RemoteCluster(Cluster):
    def __init__(self, scheduler, comm):
        self.scheduler = scheduler
        self.comm = comm
    def scale_up(self, n):
        self.comm.send({'op': 'scale-up', 'n': n})
    def scale_down(self, workers):
        self.comm.send({'op': 'scale-down', 'workers': workers})
```

We would then, from the Dask client ask the scheduler to set up an RemoteCluster, set up a local Adaptive object that uses it, and have that pair send us the information to pass onto the Skein Client.

### Skein Client with Scheduler

Alternativley we could add the Skein Client to the process running the Scheduler, empowering it to start and stop its own workers.  It would start up its own YarnCluster object, presumably providing it its own application id.  It would then receive infrequent messages from the client to change its adaptive settings (this infrastructure is already built).  

This requires less work on our part, but does mean that a Yarn container gets elevated access about its own application.  I'm not sure if this is common or not.

**Comment by mrocklin** [comment]
The active question here is probably "is it commonly acceptable for a container to be able to scale its own application"

**Comment by mrocklin** [comment]
If so, then we should probably put a YarnCluster (or similar object) within the scheduler process and just infrequently feed it small messages like `{'scale': 10}` or `{'adaptive': True}` from a client-facing RemoteCluster (or similar name) that just sends small messages when the user changes configuration.

**Comment by jcrist** [comment]
> The active question here is probably "is it commonly acceptable for a container to be able to scale its own application"

Yes. The application master is what handles all container requests, and itself runs inside a container. In the case of skein (which powers dask yarn), these requests have been abstracted out to grpc service calls which can then be made from any python process with access.

So far `dask-yarn` supports the entire `Cluster` interface (minus adaptivity) relying only on `distributed.Client` api calls. I see 2 ways forward here to support adaptivity:

1. Expose the information required to make adaptive decisions to the client. `YarnCluster` would then rely only on a connected `skein` client and `dask` client to work, and could live anywhere.

2. Push the cluster object to be a scheduler plugin, and have `YarnCluster` be a remote proxy for it. This would require a rewrite of the `YarnCluster` object, but may be better in the long run.

Option 1 might be simpler if the communication required to make adaptive decisions is low. I don't know whether that is true.

**Comment by mrocklin** [comment]
At first I was somewhat pessimistic about exposing all of the state necessary to make adaptive decisions outside of the scheduler, however now I think we can probably just have Adaptive run on the Scheduler but not be connected to any Cluster object.  Maybe our cluster uses the Dask client to query the Adaptive object periodically for its recommendations.  This may also be a more robust way to handle things for other job schedulers as well.  Any thoughts or concerns?

**Comment by mrocklin** [comment]
Here is a step towards what I'm talking about: https://github.com/dask/distributed/pull/2064

**Comment by jcrist** [comment]
I think it would be good to separate the cluster objects from needing a local scheduler in the same process.

I'm less certain if the scheduler needs to be modified in any way. AFAICT, all of the information required to make an adaptive decision is part of the `scheduler_info` call in the dask client. The size of this response does scale with the number of workers, but still shouldn't be too bad (especially if only called less than once per second). This would mean that an alternative `Adaptive` class could take a cluster object and a dask client and work fine using the client IOLoop.

I'm not sure what's best here, I suggest that you probably have better intuition on this.

**Comment by mrocklin** [comment]
Depending on the data in `scheduler_info` might work.  We've changed the adaptivity algorithms somewhat frequently in the past.  They've depended on different things at different times, including data outside of just scheduler_info.  I'd be fine with going that route, but I think that the solution pointed to above might be somewhat nicer.  It keeps all of the logic of how to adapt on the scheduler, where I think the decision is easier to make.  It allows anyone to query the scheduler for what it thinks should happen.  That external entity (here the dask/skein clients) can then act on that suggestion as necessary.

**Comment by jcrist** [comment]
Makes sense to me.
