### ISSUE TITLE
Make config dir in containers configurable

### ISSUE THREAD

**Issue by scoder** [dask/dask-yarn#12]
dask-yarn currently [sets](https://github.com/dask/dask-yarn/blob/62f700a07ce7f55f955b9af9c4587d8d74e799ac/dask_yarn/core.py#L85) the `DASK_CONFIG` directory to the fixed value `.config` in the service setup, but that directory might not always be writable. Would be nice to make that overridable.

I'm actually not so sure why that directory needs to be configured at all. Are users expected to provide persistent configuration there across container runs? If not, then why not set it to something like `/tmp`?

**Comment by jcrist** [comment]
Generally `.config` should be writable, as it should point to inside the localization directory for the application (caveat bugs/misunderstanding about yarn's undocumented internals). However, you're correct that we don't need to set this environment variable at all. I think that was left over from trying other fixes before just patching old versions of dask (https://github.com/dask/dask-yarn/blob/master/dask_yarn/_patch.py).

I'll push a PR shortly removing that environment variable, need to update dask-yarn to use skein master first.I'd expect a new release in the next day or two. If you need to get things working now, you can create your own skein spec without setting that environment variable, and pass it to `YarnCluster.from_specification`.

**Comment by jcrist** [comment]
Apologies for the delayed response here (clearly my estimate of "a day or two" was a bit off :( ). This has since been fixed, and is available in the new release (version 0.3.0). It's currently available on PyPI, and just waiting on the conda-forge CI queue to be available via conda.
