### ISSUE TITLE
Miniconda has moved

### ISSUE THREAD

**Issue by m-hinds** [dask/dask-yarn#120]
The deployment script at dask-yarn/deployment_resources/aws-emr/bootstrap-dask

uses this curl command:
`curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh`

but the minconda install has moved to:
https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

so the script fails.

**Comment by ResidentMario** [comment]
Ran into this today. 💔

Edit: looks like both of the open issues against this repo address this problem. Would be good to have one of these merged.

**Comment by jcrist** [comment]
Apologies for the delay resolving this, fixed by #117. Closing.
