### ISSUE TITLE
Getting started guide for Google Cloud Dataproc

### ISSUE THREAD

**Issue by bradmiro** [dask/dask-yarn#129]
Hello! 

I'm from the GCP Dataproc team, and we recently launched [Dask/Dask-Yarn](https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/dask) support on Dataproc. I'd like to write a getting started guide to compliment the [AWS-EMR](https://yarn.dask.org/en/latest/aws-emr.html) guide, and just want to double check that the Dask docs [contributing guidelines](https://docs.dask.org/en/latest/develop.html#contributing-to-documentation) hold true for Dask-Yarn as well. Thanks!

**Comment by jcrist** [comment]
Thanks @bradmiro, we'd definitely be interested in this. Note that due to https://github.com/dask/dask-yarn/issues/128 our CI might be a bit wonky, but for docs-only contributions things should work fine.

Let me know if you have any questions, and I look forward to seeing the new docs :).

**Comment by bradmiro** [comment]
Great, thank you!

**Comment by bradmiro** [comment]
Just opened https://github.com/dask/dask-yarn/pull/130 :)

**Comment by jcrist** [comment]
Fixed by #130.
