### ISSUE TITLE
worker_restarts does not get passed properly in core.py from __init__ to _make_specification

### ISSUE THREAD

**Issue by tmkdev** [dask/dask-yarn#13]
spec = _make_specification(environment=environment,
                                   n_workers=n_workers,
                                   worker_vcores=worker_vcores,
                                   worker_memory=worker_memory,
                                   **worker_max_restarts=worker_max_restarts,**
                                   scheduler_vcores=scheduler_vcores,
                                   scheduler_memory=scheduler_memory,
                                   name=name,
                                   queue=queue,
                                   tags=tags)

Yet _make_specification is looking for 

worker_restarts = either(**'worker_restarts'**, 'yarn.worker.restarts')

**Comment by jcrist** [comment]
Apologies for the delayed response here. This has since been fixed, and is available in the new release (version 0.3.0). It's currently available on PyPI, and just waiting on the conda-forge CI queue to be available via conda.
