### ISSUE TITLE
Verify that Read the Docs is building after master -> main

### ISSUE THREAD

**Issue by jsignell** [dask/dask-yarn#141]
Spotted on https://github.com/dask/dask-cloudprovider/issues/244#issuecomment-795310925. Read The Docs was still building `latest` from the `master` branch and builds were failing. It was configured to build from the default branch, but had cached the value `master` somewhere. Manually pointing it to  `main` in the RtD control panel fixed things.

**Comment by quasiben** [comment]
For this I think we need @jcrist to resolve .  Preferably he can add me as a maintainer and I could help here and in the future

**Comment by jcrist** [comment]
Hmmmm, I can't seem to log in to readthedocs anymore. None of my emails say they're associated with it, and the username/password I would have guessed was being used here isn't valid. I might be able to do an account recovery if I get in contact with them, but perhaps someone else already has permissions here (guessing this might be either @mrocklin or @martindurant)

**Comment by martindurant** [comment]
Sorry, not me

**Comment by jcrist** [comment]
Nevermind, figured it out. Ben, what's your readthedocs username?

**Comment by quasiben** [comment]
Thanks @jcrist !  `quasiben` is the name on rtd

**Comment by jcrist** [comment]
Sent!

**Comment by quasiben** [comment]
Thanks @jcrist !

Changed to main.  Thank you @jsignell
