### ISSUE TITLE
Add `YarnCluster.from_application_id`

### ISSUE THREAD

**Issue by jcrist** [dask/dask-yarn#16]
Would support creating a cluster object from an existing application. The process would be:

- Connect to the application using `skein.Client.connect`
- Check if the application contains the service `dask.worker` (application is indeed a dask cluster)
- Create a new `YarnCluster` object using the existing connection logic

**Comment by sauercrowd** [comment]
I'd give it a shot on the weekend if it's still open

**Comment by jcrist** [comment]
All yours!

**Comment by jcrist** [comment]
Apologies if you already started on this. I needed this for some current work, and added it in #34.

**Comment by sauercrowd** [comment]
Sorry for the late reply, no worries, thanks for adding it!
