### ISSUE TITLE
Different behaviour when using dask-yarn interactively vs. non-interactively

### ISSUE THREAD

**Issue by gg7** [dask/dask-yarn#22]
# dask_poc.py

```python
#!/usr/bin/env python

from __future__ import print_function

import logging
import os
import sys
import time

import dask_yarn
from dask.distributed import Client

logger = logging.getLogger(__name__)

VIRTUALENV_TARBALL = environment=os.path.expanduser("~/venv-dask-upstream.tar.gz")
WORKER_ENV = {"HADOOP_CONF_DIR": "/data/app/spark-yarn/hadoop-conf", "JAVA_HOME": "/usr/lib/jvm/java"}


logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s")

# Dask has issues with these
for proxy_var in ['http_proxy', 'https_proxy']:
    if proxy_var in os.environ:
        del os.environ[proxy_var]

logger.info("Initialising YarnCluster")
cluster_start_time = time.time()
cluster = dask_yarn.YarnCluster(
    VIRTUALENV_TARBALL,
    worker_vcores=1,
    worker_memory="3GB",
    worker_env=WORKER_ENV,
    n_workers=1,
    scheduler_memory="1GB")
logger.info("Initialising YarnCluster: done in %.3f", time.time() - cluster_start_time)

logger.info("Initialising Client")
client_start_time = time.time()
dask_client = Client(cluster)
logger.info("Initialising Client: done in %.3f", time.time() - client_start_time)

logger.info("Checking versions")
versions_start_time = time.time()
_versions = dask_client.get_versions(check=True)
logger.info("Checking versions: done in %.3f", time.time() - versions_start_time)

logger.info("Creating futures")
futures = dask_client.map(lambda x: x ** 2, range(4))

logger.info("Gathering futures")
print("Result: %r" % (dask_client.gather(futures),))
```

# non-interactive execution

Everything works as expected:

```
(venv-dask-upstream)george@george:~$ python dask_poc.py
[...]
Result: [0, 1, 4, 9]
```

# interactive execution

```
(venv-dask-upstream)george@george:~$ python
>>> from dask_poc import *
[...]
2018-09-17 11:02:50,823 INFO dask_poc: Initialising Client
<loops forever in https://github.com/dask/distributed/blob/1.23.1/distributed/utils.py#L274-L275 >
```

# Environment:

* CentOS 7.4.1708
* Linux 3.10.0-693.2.2.el7.x86_64
* Python 2.7.5
* Hadoop 3.1.2-SNAPSHOT (compiled from source)
* `pip freeze`:

```
asn1crypto==0.24.0
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.weakref==1.0.post1
cffi==1.11.5
click==6.7
cloudpickle==0.5.6
cryptography==2.3.1
dask==0.19.1
dask-yarn==0.3.1
decorator==4.3.0
distributed==1.23.1
enum34==1.1.6
futures==3.2.0
grpcio==1.15.0
HeapDict==1.0.0
idna==2.7
ipaddress==1.0.22
ipdb==0.11
ipython==5.8.0
ipython-genutils==0.2.0
msgpack==0.5.6
pathlib2==2.3.2
pexpect==4.6.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
protobuf==3.6.1
psutil==5.4.7
ptyprocess==0.6.0
pycparser==2.18
Pygments==2.2.0
PyYAML==3.13
scandir==1.9.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
skein==0.1.1
sortedcontainers==2.0.5
tblib==1.3.2
toolz==0.9.0
tornado==5.1
traitlets==4.3.2
venv-pack==0.2.0
wcwidth==0.1.7
zict==0.1.3
```

**Comment by jcrist** [comment]
Hmmm, both ways are semantically identical - are you sure this is repeatable and not just a coincidence that it only fails when run interactively? If not, then I'm not sure what the issue is. Many people have successfully run dask-yarn interactively with no issue, so it at least works on some systems. A few things I would check after `ctrl-c`ing out of the infinite loop:

- Is the application still running? `cluster.workers()` completing successfully would be an easy check.
- Is there anything useful in the application logs? To get the logs run `yarn logs -applicationId <app_id>` after shutting down the application (`cluster.app_id` is the application id).

> ```python
> # Dask has issues with these
> for proxy_var in ['http_proxy', 'https_proxy']:
>     if proxy_var in os.environ:
>         del os.environ[proxy_var]
> ```

Would you mind filing an issue in https://github.com/dask/distributed so this can be fixed?

**Comment by gg7** [comment]
> are you sure this is repeatable

It is repeatable, even after a restart of the whole Hadoop cluster.

> Many people have successfully run dask-yarn interactively with no issue, so it at least works on some systems.

Funnily enough, it works in ipython when using `%cpaste`, but not when using `import dask_poc`.

> Is the application still running?

According to the ResourceManager UI, it is still running after the hang.

> `cluster.workers()` completing successfully would be an easy check.

Had to change the code a bit (`cluster` wouldn't become part of `locals()` because the import got interrupted with ^C):

```diff
     logger.info("Initialising Client")
     client_start_time = time.time()
-    dask_client = Client(cluster)
+    try:
+        dask_client = Client(cluster)
+    except:
+        logger.info("cluster.workers(): %r", cluster.workers())
+        raise
     logger.info("Initialising Client: done in %.3f", time.time() - client_start_time)
```

Result:

```
2018-09-18 11:13:04,063 INFO dask_poc: Initialising Client
^C2018-09-18 11:13:54,983 INFO dask_poc: cluster.workers(): [Container<service_name=u'dask.worker', instance=0, state=RUNNING>]
```

> Is there anything useful in the application logs? To get the logs run `yarn logs -applicationId <app_id>` after shutting down the application

That command didn't work for me, but these ones did:

```
$ hdfs dfs -ls /app-logs/george/logs/application_1537261967824_0006
Found 3 items
-rw-r-----   3 george hadoop       8999 2018-09-18 11:18 /app-logs/george/logs/application_1537261967824_0006/server1_34262
-rw-r-----   3 george hadoop     166497 2018-09-18 11:18 /app-logs/george/logs/application_1537261967824_0006/server2_38203
-rw-r-----   3 george hadoop     166820 2018-09-18 11:18 /app-logs/george/logs/application_1537261967824_0006/server3_39530
```

Potentially interesting:

```
$ hdfs dfs -cat /app-logs/george/logs/application_1537261967824_0006/server2_38203 | view -
[...]
+ dask-yarn-scheduler
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:   tcp://1.1.1.1:37733
distributed.scheduler - INFO - Register tcp://2.2.2.2:35102
distributed.scheduler - INFO - Starting worker compute stream, tcp://2.2.2.2:35102
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Receive client connection: Client-6e240f23-bb2b-11e8-a581-fa163ebd8022
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Remove client Client-6e240f23-bb2b-11e8-a581-fa163ebd8022
distributed.scheduler - INFO - Remove client Client-6e240f23-bb2b-11e8-a581-fa163ebd8022
distributed.scheduler - INFO - Close client connection: Client-6e240f23-bb2b-11e8-a581-fa163ebd8022
distributed.scheduler - INFO - Remove worker tcp://2.2.2.2:35102
distributed.core - INFO - Removing comms to tcp://2.2.2.2:35102
distributed.scheduler - INFO - Lost all workers
```

And

```
$ hdfs dfs -cat /app-logs/george/logs/application_1537261967824_0006/server3_39530 | view -
[...]
+ dask-yarn-worker
distributed.nanny - INFO -         Start Nanny at: 'tcp://2.2.2.2:39072'
distributed.worker - INFO -       Start worker at:    tcp://2.2.2.2:35102
distributed.worker - INFO -          Listening to:    tcp://2.2.2.2:35102
distributed.worker - INFO -              nanny at:          2.2.2.2:39072
distributed.worker - INFO - Waiting to connect to:    tcp://1.1.1.1:37733
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    3.07 GB
distributed.worker - INFO -       Local Directory: /censored
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:    tcp://1.1.1.1:37733
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.nanny - INFO - Closing Nanny at 'tcp://2.2.2.2:39072'
distributed.process - WARNING - reaping stray process <Process(Process-1, started daemon)>
```

> Would you mind filing an issue [about `http(s)_proxy`]

That might not be worth fixing.

**Comment by jcrist** [comment]
None of those logs look odd to me - the cluster is starting up fine, the client is just failing to connect. I doubt this is an issue with dask-yarn specifically (and am a bit baffled how this behavior is even possible). Two more things I'd try:

- Remove connecting to the cluster from your startup script. Then connect to the cluster using the address directly. Something like:

```python
from __future__ import print_function

import logging
import os
import sys
import time

import dask_yarn
from dask.distributed import Client

logger = logging.getLogger(__name__)

VIRTUALENV_TARBALL = environment=os.path.expanduser("~/venv-dask-upstream.tar.gz")
WORKER_ENV = {"HADOOP_CONF_DIR": "/data/app/spark-yarn/hadoop-conf", "JAVA_HOME": "/usr/lib/jvm/java"}


logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s")

# Dask has issues with these
for proxy_var in ['http_proxy', 'https_proxy']:
    if proxy_var in os.environ:
        del os.environ[proxy_var]

logger.info("Initialising YarnCluster")
cluster_start_time = time.time()
cluster = dask_yarn.YarnCluster(
    VIRTUALENV_TARBALL,
    worker_vcores=1,
    worker_memory="3GB",
    worker_env=WORKER_ENV,
    n_workers=1,
    scheduler_memory="1GB")
logger.info("Initialising YarnCluster: done in %.3f", time.time() - cluster_start_time)
```

And in your session

```
from dask_poc import cluster
from dask.distributed import Client

client = Client(cluster.scheduler_address)
# May also equally try client = Client(cluster)
```

I'd also look at the scheduler address and see if it's reachable from your edge node, and if the address looks proper.

- Start a scheduler locally, and just try connecting to it:

In one terminal:

```
dask-scheduler
```

In another terminal

```
from dask.distributed import Client

client = Client(address_output_in_the_first_terminal)
```

**Comment by rmunoz527** [comment]
I too am experiencing the issue in interactive mode. Funny about the snippet regarding distributed and http_proxy. Is that a requirement to run dask-yarn?  Since I am new to dask and dived head first into dask-yarn, i might have skipped some required configuration to get distributed to work.

**Comment by gg7** [comment]
@jcrist Thanks, I'll look into that soon.

@rmunoz527 If you're behind a corporate proxy and `http_proxy` or `https_proxy` are defined, undefine them.

**Comment by rmunoz527** [comment]
Thats what's strange is http_proxy are not defined, but the exception i saw
was that it couldn't parse the empty field, so I thought it was expecting
it.

**Comment by jcrist** [comment]
A new version of dask-yarn/skein has been released with several bugfixes. I'm unsure if it will fix your issue, as I'm unable to reproduce your issue. Please try it out and let me know.

**Comment by rmunoz527** [comment]
Hi Jim,

I have worked past the issue, it was my own lack of understanding on how to
deploy. I was able to get things working successfully with a python 2.7
distributed virtual environment. Thanks for your help! -Robert

**Comment by jcrist** [comment]
@rmunoz527, glad to hear it.

@gg7, any updates? Planning on closing in 7 days if no comment.

**Comment by gg7** [comment]
@jcrist Apologies, I've been busy with other projects.

In the end I standardised on Apache Spark for my YARN cluster. I'll likely have another look at DASK in the future. Thanks for open-sourcing this project anyway!

**Comment by aflag** [comment]
fwiw, I wasn't able to reproduce the issue with the latest version of Dask in a bare metal yarn cluster.
