### ISSUE TITLE
Unable to load libhdfs, can anyone help to sort it out, thank you very much.

### ISSUE THREAD

**Issue by mdivk** [dask/dask-yarn#31]
Trying to use pyarrow to access hdfs file and not able to get it working, below is the code, thank you very much in advance.

[rxie@cedgedev03 code]$ python
Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:42:40)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pyarrow
>>> import os
>>> os.environ["JAVA_HOME"]="/usr/java/jdk1.8.0_121"
>>> from pyarrow import hdfs
>>> fs = hdfs.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/pyarrow/hdfs.py", line 183, in connect
    extra_conf=extra_conf)
  File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/pyarrow/hdfs.py", line 37, in __init__
    self._connect(host, port, user, kerb_ticket, driver, extra_conf)
  File "pyarrow/io-hdfs.pxi", line 89, in pyarrow.lib.HadoopFileSystem._connect
  File "pyarrow/error.pxi", line 83, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: Unable to load libhdfs

**Comment by jcrist** [comment]
This is not an issue with dask-yarn, but with pyarrow itself. I suggest consulting the [pyarrow documentation](https://arrow.apache.org/docs/python/filesystems.html#hadoop-file-system-hdfs). See also [this comment](https://github.com/dask/dask-yarn/issues/20#issuecomment-419129981).

**Comment by mdivk** [comment]
alright, thank you.
