### ISSUE TITLE
AWS EMR yarn-cluster seems to ignore worker_vcore param 

### ISSUE THREAD

**Issue by mnapolitano89** [dask/dask-yarn#48]
Sorry for the bare bones issue, I'd be happy to flesh out more but I'm not sure where to start providing data. I also suspect this might be a skein bug, but I'm not sure - happy to point it in their direction if that is the case

When creating a YarnCluster and specifying worker_vcores, the scheduler starts up fine, but no workers instantiate (either via a scale or by specifying initial n_workers). The application logs look like there's a mismatch between what containers are being requested and what skein wants, which points to a problem on there end, but I'm not too sure and figured I'd start here. Any ideas for additional things to look for?

Specifying worker_memory works fine, but will always end up having only 1 core per container regardless of how much memory you give it, so you end up with situations where there's 10 containers with 100gb of ram each only using 1 core. Pains me inside :)

Thanks, 
Michael 

```
19/01/15 19:04:25 INFO skein.ApplicationMaster: Application specification successfully loaded
19/01/15 19:04:25 INFO skein.ApplicationMaster: Running as user hadoop
19/01/15 19:04:25 INFO client.RMProxy: Connecting to ResourceManager at ip-10-201-102-148.ginkgobioworks.com/10.201.102.148:8030
19/01/15 19:04:25 INFO impl.ContainerManagementProtocolProxy: yarn.client.max-cached-nodemanagers-proxies : 0
19/01/15 19:04:25 INFO skein.ApplicationMaster: gRPC server started at ip-10-201-102-157.ginkgobioworks.com:42873
19/01/15 19:04:25 INFO skein.ApplicationMaster: WebUI server started at ip-10-201-102-157.ginkgobioworks.com:32841
19/01/15 19:04:25 INFO client.RMProxy: Connecting to ResourceManager at ip-10-201-102-148.ginkgobioworks.com/10.201.102.148:8032
19/01/15 19:04:25 INFO skein.ApplicationMaster: Initializing service 'dask.worker'.
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_0
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_1
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_2
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_3
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_4
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_5
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_6
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_7
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_8
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_9
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_10
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_11
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_12
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_13
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_14
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_15
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_16
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_17
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_18
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_19
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_20
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_21
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_22
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_23
19/01/15 19:04:25 INFO skein.ApplicationMaster: REQUESTED: dask.worker_24
19/01/15 19:04:27 INFO impl.AMRMClientImpl: Received new token for : ip-10-201-102-157.ginkgobioworks.com:8041
19/01/15 19:04:27 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 1, releasing container_1547573448325_0009_01_000002
19/01/15 19:04:28 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 2, releasing container_1547573448325_0009_01_000003
19/01/15 19:04:29 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 3, releasing container_1547573448325_0009_01_000004
19/01/15 19:04:30 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 4, releasing container_1547573448325_0009_01_000005
19/01/15 19:04:31 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 5, releasing container_1547573448325_0009_01_000006
19/01/15 19:04:32 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 6, releasing container_1547573448325_0009_01_000007
19/01/15 19:04:33 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 7, releasing container_1547573448325_0009_01_000008
19/01/15 19:04:34 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 8, releasing container_1547573448325_0009_01_000009
19/01/15 19:04:35 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 9, releasing container_1547573448325_0009_01_000010
19/01/15 19:04:36 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 10, releasing container_1547573448325_0009_01_000011
19/01/15 19:04:37 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 11, releasing container_1547573448325_0009_01_000012
19/01/15 19:04:38 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 12, releasing container_1547573448325_0009_01_000013
19/01/15 19:04:39 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 13, releasing container_1547573448325_0009_01_000014
19/01/15 19:04:40 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 14, releasing container_1547573448325_0009_01_000015
19/01/15 19:04:41 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 15, releasing container_1547573448325_0009_01_000016
19/01/15 19:04:42 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 16, releasing container_1547573448325_0009_01_000017
19/01/15 19:04:43 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 17, releasing container_1547573448325_0009_01_000018
19/01/15 19:04:44 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 18, releasing container_1547573448325_0009_01_000019
19/01/15 19:04:45 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 19, releasing container_1547573448325_0009_01_000020
19/01/15 19:04:46 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 20, releasing container_1547573448325_0009_01_000021
19/01/15 19:04:47 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 21, releasing container_1547573448325_0009_01_000022
19/01/15 19:04:48 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 22, releasing container_1547573448325_0009_01_000023
19/01/15 19:04:49 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 23, releasing container_1547573448325_0009_01_000024
19/01/15 19:04:50 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 24, releasing container_1547573448325_0009_01_000025
19/01/15 19:04:51 WARN skein.ApplicationMaster: No matching service found for resource <memory:2048, vCores:1>, priority 25, releasing container_1547573448325_0009_01_000026
```

**Comment by jcrist** [comment]
Hmmm, that does look odd. The `WARN` logs are due to a weird yarn bug where sometimes containers are received that don't match the existing specification at all. In skein we do a bit of a hack to get around this bug. I rarely see this log anymore, even when specifying multiple `vcores`. I suspect this is specific to your install.

A few questions:

- What version of `dask-yarn`, `skein`, and `python` are you using?
- From the logs above I'd guess that you never actually get workers allocated, the request for a container for a worker returns a container that is smaller than the request, resulting in a container being dropped. Is this the case?
- What EMR configuration are you using (AMI, node types, etc...)?

**Comment by mnapolitano89** [comment]
1. Python is 3.6.8, skein is 0.5.0 and dask-yarn is 0.5.1
2. That does seem to be the case. Looking at the yarn logs, I can see a corresponding set of launches for too-small containers
`2019-01-15 19:04:27,720 INFO org.apache.hadoop.yarn.server.resourcemanager.scheduler.SchedulerNode (ResourceManager Event Processor): Assigned container container_1547573448325_0009_01_000002 of capacity <memory:2048, vCores:1> on host ip-10-201-102-157.ginkgobioworks.com:8041, which has 2 containers, <memory:2560, vCores:2> used and <memory:775680, vCores:94> available after allocation`. I'm not sure where to look to see what was requested of it though
3. EMR configuration is:
emr-5.20.0
Amazon 2.8.5
running on a core r5.24xl, and a master m5.25xl (and scales up and down - I've had as much as 10 core nodes and a master, all show the same behavior). It uses the EMR bootstrap script with a few extra packages, but it doesn't touch the yarn confs. 

I think the skein client is trying to ask for the right thing, but I don't know how to view what it's asking the yarn scheduler for. The node manager logs look normalish, except for some warns like this:
`2019-01-15 21:51:17,913 WARN org.apache.hadoop.yarn.server.nodemanager.containermanager.ContainerManagerImpl (AsyncDispatcher event handler): couldn't find container container_1547573448325_0012_01_000002 while processing FINISH_CONTAINERS event
2`, but that might be because they're already killed by someone?

**Comment by mnapolitano89** [comment]
For what it's worth, the cluster application client specification / services seems right
`'{"resources": {"memory": 2048, "vcores": 9}, "script": "bash .skein.sh ><LOG_DIR>/dask.worker.log 2>&1", "instances": 25, "files": {".skein.pem": {"source": "hdfs://ip-10-201-102-148.ginkgobioworks.com:8020/user/hadoop/.skein/application_1547573448325_0013/.skein.pem", "type": "FILE", "visibility": "APPLICATION", "size": 1704, "timestamp": 1547589191256}, ".skein.sh": {"source": "hdfs://ip-10-201-102-148.ginkgobioworks.com:8020/user/hadoop/.skein/application_1547573448325_0013/dask.worker.sh", "type": "FILE", "visibility": "APPLICATION", "size": 57, "timestamp": 1547589191666}, ".skein.crt": {"source": "hdfs://ip-10-201-102-148.ginkgobioworks.com:8020/user/hadoop/.skein/application_1547573448325_0013/.skein.crt", "type": "FILE", "visibility": "APPLICATION", "size": 1013, "timestamp": 1547589190844}, "environment": {"source": "hdfs://ip-10-201-102-148.ginkgobioworks.com:8020/user/hadoop/.skein/application_1547573448325_0013/2CA382FC6CA917E30E1EE0AE47DCA128/environment.tar.gz", "type": "ARCHIVE", "visibility": "APPLICATION", "size": 331418323, "timestamp": 1547589192232}}, "env": {"LANG": "en_US.UTF-8", "ARROW-LIBHDFS-DIR": "/usr/lib/hadoop/lib/native/"}, "depends": [], "max_restarts": -1, "node_label": "", "nodes": [], "racks": [], "relax_locality": false}'`

**Comment by jcrist** [comment]
Hmmm, one thought: by default yarn limits the number of vcores per container to 4. Per the docs requesting a larger container should error, but the docs have been consistently wrong so who knows. I see you're requesting 9 cores above, have you tried something smaller like 2?

**Comment by mnapolitano89** [comment]
Same problem with 2 cores :-/

**Comment by jcrist** [comment]
Ok, thanks for providing a good issue. I'll try to reproduce this tomorrow.

**Comment by Dimplexion** [comment]
Hey, just wanted to chime in that I'm seeing the exact same behavior. Setting the memory works perfectly but the only setting that works for worker_vcores is `1`, otherwise the containers fail with `WARN skein.ApplicationMaster: No matching service found for resource`.

I'm running it on a cluster of 6 `m3.xlarge`s with a `m3.xlarge` master node. Each node should have 8 vcpus available and if I set the `worker_vcores` to `1` it is able to spawn multiple containers on each node. However each of them can only run a single thread.

In my case the skein `ApplicationSpec` seems correct too:
```
{
	"services": {
		"dask.scheduler": {
			"resources": {
				"memory": 2048,
				"vcores": 1
			},
			"script": "source environment/bin/activate\ndask-yarn services scheduler",
			"instances": 1,
			"files": {
				"environment": {
					"source": "file:///home/ec2-user/dask_env.tar.gz",
					"type": "ARCHIVE",
					"visibility": "APPLICATION",
					"size": 0,
					"timestamp": 0
				}
			},
			"env": {},
			"depends": [],
			"max_restarts": 0,
			"node_label": "",
			"nodes": [],
			"racks": [],
			"relax_locality": false
		},
		"dask.worker": {
			"resources": {
				"memory": 10240,
				"vcores": 4
			},
			"script": "source environment/bin/activate\ndask-yarn services worker",
			"instances": 1,
			"files": {
				"environment": {
					"source": "file:///home/ec2-user/dask_env.tar.gz",
					"type": "ARCHIVE",
					"visibility": "APPLICATION",
					"size": 0,
					"timestamp": 0
				}
			},
			"env": {},
			"depends": ["dask.scheduler"],
			"max_restarts": -1,
			"node_label": "",
			"nodes": [],
			"racks": [],
			"relax_locality": false
		}
	},
	"master": {
		"resources": {
			"memory": 512,
			"vcores": 1
		},
		"script": "",
		"files": {},
		"env": {},
		"log_level": "INFO"
	},
	"name": "dask",
	"queue": "default",
	"user": "",
	"node_label": "",
	"tags": [],
	"file_systems": [],
	"acls": {
		"enable": false,
		"view_users": [],
		"view_groups": [],
		"modify_users": [],
		"modify_groups": [],
		"ui_users": []
	},
	"max_attempts": 1
}
```

**Comment by jcrist** [comment]
Thanks for the additional information. I am able to reproduce on EMR but not locally. Right now I'm assuming this is a difference between hadoop 2.6 (the version we test skein with) and 2.8.5 (EMR's version). Debugging now.

**Comment by mnapolitano89** [comment]
I booted up an EMR instance on hadoop 2.6 [emr-4.2.0], and shows the same behavior

**Comment by jcrist** [comment]
Found the issue. Some YARN configurations always return resources with vcores == 1 (even though the started application is free to use the number of vcores requested). This bit spark a while ago: https://issues.apache.org/jira/browse/SPARK-6050. Fixing now.

**Comment by jcrist** [comment]
Should be fixed by https://github.com/jcrist/skein/pull/131

**Comment by jcrist** [comment]
The patch has been merged and tested on EMR. I'll get a release of skein out today with this patch (will update here when that happens). Thanks all!

**Comment by jcrist** [comment]
Sorry, pushed a few more fixes before releasing. Skein 0.5.1 has now been released, and includes this fix. It's available now on PyPI, and will be shortly on conda-forge.

**Comment by mnapolitano89** [comment]
Seems to be working great! CPU usages are now getting above 100% / container!

**Comment by manugarri** [comment]
@mnapolitano89 seemingly random question (that i will move to a separate issue if required), I have noticed that when uploading eggs with `upload_files`  , the workers are killed  whenever I specify the number of worker_vcores at cluster creation, but not when I use the defaults. They seem to be unable to import the uploaded egg module.

Have you experienced this issue?  I am not sure if its a dask/yarn or an skein issue.

Thanks a lot for any info you can provide

**Comment by jcrist** [comment]
This is a separate issue, would you mind opening a new issue? It would be useful if you could provide the worker logs from a failed attempt as well (you may want to glance through them before posting to remove any sensitive details (urls, etc...)). You can get the logs with:

```
$ yarn logs -applicationId <APPID>
```

where `<APPID>` is the application id (`cluster.app_id`).
