### ISSUE TITLE
hdfs configuration as step on EMR

### ISSUE THREAD

**Issue by nmerket** [dask/dask-yarn#66]
First, thank you for this awesome library. It's been a game changer for me to be able to run dask clusters on EMR. 

First, I'm using your EMR bootstrap script to set up the cluster. I have a bunch of large zip files (~2 GB) on s3 that I'm pulling smaller individual csv files out of and processing into a dask dataframe. I'm [copying the data](https://docs.aws.amazon.com/emr/latest/ReleaseGuide/UsingEMR_s3distcp.html) from s3 into hdfs before processing. 

I can open a notebook as advertised and open a hdfs connection as follows with no problem.

```python
import pyarrow as pa
fs = pa.hdfs.connect()
```

I'm able to do the same on the workers from within the notebook. So far this works great.

Where I run into a problem is that I want to [run this as a script](https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-hadoop-script.html) unattended as an EMR step instead of the notebook. However, when I do so it produces the following error on the same line

```
pyarrow.lib.ArrowIOError: HDFS connection failed
```

It seems like something is getting configured for the jupyter notebook server that isn't for the standalone job step, I'm just having a hard time pinning it down. Any ideas?

**Comment by jcrist** [comment]
Apologies for the delayed response. Glad `dask-yarn` has been useful for you! Your issue is likely due to `pyarrow` not being able to find the required native hadoop libraries. Setting the following environment variable should fix things:

```python
import os
os.environ['ARROW_LIBHDFS_DIR'] = '/usr/lib/hadoop/lib/native/'
```

**Comment by jcrist** [comment]
Closing as stale, feel free to reopen if the issue persists.

**Comment by bschreck** [comment]
@jcrist I'm seeing a similar problem. I think I have all env vars set correctly, and can connect to pyarrow in the notebook fine.

```
from dask_yarn import YarnCluster
from dask.distributed import Client


cluster = YarnCluster(worker_env={'ARROW_LIBHDFS_DIR': '/usr/lib/hadoop/lib/native/'},
                      name='dask_yarn_cluster',
                      deploy_mode='local',
                      worker_memory='120GiB',
                      worker_vcores=16,
                      n_workers=9,
                      environment= '/home/hadoop/environment.tar.gz')

client = Client(cluster)

def connect_remotely():
    import pyarrow
    fs = pyarrow.hdfs.connect()
    return fs.ls('.')
def load_env_vars():
    import os
    return [os.environ[v] for v in ['HADOOP_HOME', 'JAVA_HOME', 'ARROW_LIBHDFS_DIR', 'HADOOP_CLASSPATH']]

res = client.compute(delayed(load_env_vars)())
res.result()
```

This returns:

```
['/usr/lib/hadoop',
 '/usr/lib/jvm/java-openjdk',
 '/usr/lib/hadoop/lib/native/',
 ':/usr/lib/hadoop-lzo/lib/*:/usr/share/aws/aws-java-sdk/*:/usr/share/aws/emr/emrfs/conf:/usr/share/aws/emr/emrfs/lib/*:/usr/share/aws/emr/emrfs/auxlib/*:/usr/share/aws/emr/ddb/lib/emr-ddb-hadoop.jar:/usr/share/aws/emr/goodies/lib/emr-hadoop-goodies.jar:/usr/share/aws/emr/kinesis/lib/emr-kinesis-hadoop.jar:/usr/share/aws/emr/cloudwatch-sink/lib/*:/usr/share/aws/emr/security/conf:/usr/share/aws/emr/security/lib/*:/usr/lib/hadoop-lzo/lib/*:/usr/share/aws/aws-java-sdk/*:/usr/share/aws/emr/emrfs/conf:/usr/share/aws/emr/emrfs/lib/*:/usr/share/aws/emr/emrfs/auxlib/*:/usr/share/aws/emr/ddb/lib/emr-ddb-hadoop.jar:/usr/share/aws/emr/goodies/lib/emr-hadoop-goodies.jar:/usr/share/aws/emr/kinesis/lib/emr-kinesis-hadoop.jar:/usr/share/aws/emr/cloudwatch-sink/lib/*:/usr/share/aws/emr/security/conf:/usr/share/aws/emr/security/lib/*']
```

However, trying to connect within a worker delayed function:

```
res = client.compute(delayed(connect_remotely)())
res.result()
```

```
---------------------------------------------------------------------------
ArrowIOError                              Traceback (most recent call last)
<ipython-input-23-56f5f02e1a25> in <module>
      1 res = client.compute(delayed(connect_remotely)())
----> 2 res.result()

~/miniconda/lib/python3.7/site-packages/distributed/client.py in result(self, timeout)
    220         result = self.client.sync(self._result, callback_timeout=timeout, raiseit=False)
    221         if self.status == "error":
--> 222             six.reraise(*result)
    223         elif self.status == "cancelled":
    224             raise result

~/miniconda/lib/python3.7/site-packages/six.py in reraise(tp, value, tb)
    690                 value = tp()
    691             if value.__traceback__ is not tb:
--> 692                 raise value.with_traceback(tb)
    693             raise value
    694         finally:

<ipython-input-20-49ee4e2b39e5> in connect_remotely()
      1 def connect_remotely():
      2     import pyarrow
----> 3     fs = pyarrow.hdfs.connect()
      4     return fs.ls('.')
      5 def load_env_vars():

/mnt3/yarn/usercache/hadoop/appcache/application_1566938397423_0011/container_1566938397423_0011_01_000005/environment/lib/python3.7/site-packages/pyarrow/hdfs.py in connect()

/mnt3/yarn/usercache/hadoop/appcache/application_1566938397423_0011/container_1566938397423_0011_01_000005/environment/lib/python3.7/site-packages/pyarrow/hdfs.py in __init__()

~/miniconda/lib/python3.7/site-packages/pyarrow/io-hdfs.pxi in pyarrow.lib.HadoopFileSystem._connect()
    103 
    104         with nogil:
--> 105             check_status(CHadoopFileSystem.Connect(&conf, &self.client))
    106         self.is_open = True
    107 

~/miniconda/lib/python3.7/site-packages/pyarrow/error.pxi in pyarrow.lib.check_status()
     85             raise ArrowInvalid(message)
     86         elif status.IsIOError():
---> 87             raise ArrowIOError(message)
     88         elif status.IsOutOfMemory():
     89             raise ArrowMemoryError(message)

ArrowIOError: HDFS connection failed
```

I checked the workers themselves, and they do seem to have all the proper env vars set

**Comment by bschreck** [comment]
Update: when I ssh in to the workers, they don't have ARROW_LIBHDFS_DIR set by default in the terminal. After setting it, I can get pyarrow to connect. However, I can't figure out how to get Dask-Yarn to set it on these workers.

**Comment by nmerket** [comment]
@jcrist I'm still having this problem. The minimum reproducible example is to use your [bootstrap-dask](https://github.com/dask/dask-yarn/blob/master/deployment_resources/aws-emr/bootstrap-dask) script to run dask-yarn on EMR as per [these instructions](https://yarn.dask.org/en/latest/aws-emr.html). Open a notebook, create a dask dataframe in any way you would like and then try to write it out on hdfs as in:

```
import dask.dataframe as dd
df = dd.read_whatever(...)
df.to_parquet('hdfs://somewhere', engine='pyarrow')
```

It returns an `ArrowIOError: HDFS connection failed` error. 

It looks like you're trying to set those environment variables you mentioned earlier in the bootstrap script [here](https://github.com/dask/dask-yarn/blob/8f5f97418ddf3287f00be2762a195499010bc3c8/deployment_resources/aws-emr/bootstrap-dask#L159-L168), but it is not having the desired effect.
