### ISSUE TITLE
broken compatibility with distributed 2.2.0

### ISSUE THREAD

**Issue by AJIEIIIA** [dask/dask-yarn#87]
dask-yarn doesn't seem to be compatible with distributed 2.2.0.
The reason seems to be this [change](https://github.com/dask/distributed/commit/96ff5d3409c0146759cdc68a43d86c96e159daa4#diff-6a3108098afcddf88b38652ae1e383b5R1181):

which then breaks this piece of code here:
https://github.com/dask/dask-yarn/blob/master/dask_yarn/cli.py#L316

so that whenever scheduler is attempted to be started it crashes with:

TypeError: start() takes exactly 1 positional argument (2 given)

Sorry cannot give full call stack right now, but can provide, if needed. Anyway, the problem is clear I think.

**Comment by jcrist** [comment]
Yep, I hope to get a new compatible release out by EOD.

**Comment by jcrist** [comment]
Version 0.7.0 has been released, and is compatible with the new distributed release. Available on PyPI and shortly on conda-forge.

**Comment by AJIEIIIA** [comment]
thanks for fixing this so quickly!
