### ISSUE TITLE
Provide information about what to do if you're not on an edge node

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-yarn#9]
Do we have a pragmatic recommendation today for users that don't have direct access to an edge node?

**Comment by jcrist** [comment]
Not currently. Currently skein requires two things that (as far as I know) are unlikely to be true not on an edge node:

- Have the hadoop java libraries installed, and the hadoop configuration files available.
- Have access to the resourcemanager rpc port

I'm not sure if any other tools work off the edge node without some third service to mediate (e.g. livy). Filed https://github.com/jcrist/skein/issues/28 to see if anyone has used something like this.

One (hacky) solution might be to use paramiko to start and manage ssh tunnels and run the required commands remotely. This would still require access to an edge node though, just ease the process for users wanting to run their client locally. I'm hesitant to do this though, as it adds complexity to the library that I'm hoping to avoid.

**Comment by jcrist** [comment]
After talking to more people about this, I don't believe we'll have an answer to this for a while. The documentation notes that this is for use on an edge node. Solutions for running not on an edge node will likely require an external service running with elevated permissions. See https://github.com/dask/distributed/issues/2043 for more discussion.

Closing for now. More issues can be opened later as needed.
