### ISSUE TITLE
Cluster dashboard_link report proxy link

### ISSUE THREAD

**Issue by birdsarah** [dask/dask-yarn#96]
When starting dask yarn cluster and jupyter-server-proxy is available it would be great if cluster could report back the proxy dashboard link for easy use with dask labextension.

**Comment by mrocklin** [comment]
You can probably set this with the config value distributed.dashboard.link

**Comment by mrocklin** [comment]
(at least this is how this is handlled in most cluster managers, I'm not
fully confident about dask-yarn in particular)

**Comment by jcrist** [comment]
Yeah, everything's the same here. You'd want to set `distributed.dashboard.link` - for example we do this in the [EMR bootstrap script](https://github.com/dask/dask-yarn/blob/cf36384f437e602f459383b38e620da4b6105ad8/deployment_resources/aws-emr/bootstrap-dask#L151-L153).

**Comment by birdsarah** [comment]
very good. thanks.

New thought: Would it be reasonable to pass this setting to `YarnCluster` as a parameter or `Client` - this is easier to share with new people than a readme that asks a user to add a config file (I am trying to win hearts and minds :D)

**Comment by birdsarah** [comment]
Relatedly I've also seen instances where users don't have access to command line (big bank IT) to set things like this. Although in theory they could write the file with python.

**Comment by jcrist** [comment]
Historically we've opted for adding this configuration to users environments in a transparent way (e.g. in the EMR bootstrap file). You could package it as part of a user's conda environment (dask also loads any config files found in `"{sys.prefix}/etc/dask/*.yaml"`). You could also set it as an environment variable:  `DASK_DISTRIBUTED__DASKBOARD__LINK="/proxy/{port}/status"`. Or if your users are using a library, you could set it programmatically using `dask.config.set`. Given the varied ways people deploy dask, I'm unlikely to add a kwarg to set just this one configuration parameter when there are several existing ways to handle this configuration.

**Comment by birdsarah** [comment]
`dask.config.set` is perfect. Thanks.

Additionally / relatedly if we could make a daskyarn interface for dask-jupyterlab then things would / should just work. (I know PRs welcome :D)

**Comment by birdsarah** [comment]
One last thought. I only realized this week that I could use the proxy link with DaskYarn and how to. I have been re-sshing into my servers with 2fa every time i start a new cluster so that i can port forward the dashboard.

Just a thought to maybe better highlight this in docs if you see a spot. I feel like you've recently updated the docs, I'm not sure. But I just noticed that there's no example that specifies the deploy='local' option which i wouldn't have figured out by myself.

Additionally, I don't get a pretty cluster gui when i print the gui - i get 

![Screenshot from 2019-08-28 13-16-45](https://user-images.githubusercontent.com/1796208/63881465-89293500-c995-11e9-8b36-6be9c133c81f.png)

Sorry for the ramblings. Nothing to do here just some thoughts i may come back to.

**Comment by jcrist** [comment]
These are all good points, thanks for bringing them up.

> Additionally, I don't get a pretty cluster gui when i print the gui - i get

You need `ipywidgets` installed to get the nice gui, otherwise we just do a simple repr.

**Comment by birdsarah** [comment]
> You need ipywidgets installed to get the nice gui, otherwise we just do a simple repr.

Right. Of course! This is also true for progress bar. I'm wierdly resistant to adding it to my conda env. I will have to think about this.

**Comment by jcrist** [comment]
In dask-gateway I added a fallback html repr for users without `ipywidgets` (https://github.com/jcrist/dask-gateway/pull/70#issue-303163639). It's not interactive, but at least provides the dashboard link. It's also just a grey box, and could use some styling help (hint hint :)). Could definitely add something like this to dask-yarn/other cluster managers.

**Comment by mrocklin** [comment]
Ooh, can we have the fallback repr upstream?

**Comment by jcrist** [comment]
Sure thing.
