### ISSUE TITLE
Bug in the bootstrap-dask script

### ISSUE THREAD

**Issue by ankur-gupta** [dask/dask-yarn#97]
- **A description of the bug**
Extra trailing backslash on https://github.com/dask/dask-yarn/blob/master/deployment_resources/aws-emr/bootstrap-dask#L199 

```
if [[ "$JUPYTER" == "true" ]]; then
    echo "Installing Jupyter"
    conda install \
    -c conda-forge \
    -y \
    -q \
    notebook \
    ipywidgets \
    jupyter-server-proxy \ # <- This slash
fi
```

- **Steps to reproduce** 
Run the bootstrap-dask script

- **Relevant logs/tracebacks**
```
/emr/instance-controller/lib/bootstrap-actions/1/bootstrap-dask: line 246: syntax error: unexpected end of file
```

**Comment by jcrist** [comment]
Thanks for the excellent issue report, would you mind submitting a PR fixing this?

**Comment by ankur-gupta** [comment]
Thanks. Yes, I will submit a PR.
