### ISSUE TITLE
Specify port or range of ports to use for scheduler/dashboard

### ISSUE THREAD

**Issue by bschreck** [dask/dask-yarn#99]
Is this currently possible? It seems YarnCluster initializes a Scheduler without the port argument and thus returns a random port. My use case is on a heavily locked down EMR cluster, and can only open up certain ports to the outside. I'd like to be able to specify a range of ports the scheduler is allowed to use

**Comment by jcrist** [comment]
This currently isn't possible. Usually people use dask-yarn from within the cluster firewall, and proxy out the dashboard if needed (using either ssh port forwarding, or jupyter-server-proxy). Are you trying to connect a client to a dask cluster from outside the cluster?

**Comment by bschreck** [comment]
Yes, from a sagemaker notebook within the same VPC. So we're trying to open up the security group on EMR to the one on the sagemaker notebook

**Comment by bschreck** [comment]
How does it choose the ports? What part of the stack is responsible for that? Distributed, Skein, or YARN?

**Comment by jcrist** [comment]
How are you starting the dask cluster then if you're connecting to it from sagemaker? Extra workflow step?

> How does it choose the ports? What part of the stack is responsible for that? Distributed, Skein, or YARN?

This would be an extra setting in `YarnCluster`. I'd be fine with adding it, I'm just trying to understand the use case here.

**Comment by bschreck** [comment]
Yeah we start it separately when we launch the cluster. Via dask_labextension actually

**Comment by bschreck** [comment]
And ideally we'd want to specify the dashboard port too

**Comment by jcrist** [comment]
>  Via dask_labextension actually

Wait, I'm confused. Let step back to clarify here. Say you have an EMR cluster with 3 nodes (1 master, 2 compute nodes), and also wherever your notebook server is running (on sagemaker?). There's a firewall around the EMR cluster that only lets out a few ports. How can you start a cluster using `dask_labextension` from the notebook, when the notebook server isn't running inside the EMR cluster? `dask-yarn` requires access the the java hadoop libraries, config, and ports, all of which can only usually be accessed from within the same cluster. Do sagemaker nodes act as an edge node in these cases (I'm not familiar with sagemaker at all, this may be a silly question)?

**Comment by bschreck** [comment]
Yup that was confusing. We don't start it from the Sagemaker notebook. We also have a Jupyter Lab instance running inside the cluster's master node. This is helpful for our dev environment but it's locked down on prod. We still start it up on prod though, just so the two environments are identical.

**Comment by bschreck** [comment]
So the Jupyter Lab instance starts up via our bootstrap script when we launch the cluster, and in so doing creates an initial dask cluster. We currently would have to re-submit the bootstrap step to restart a cluster

**Comment by jcrist** [comment]
Hmmm, ok. I'm happy to add this option to dask-yarn, others have asked for something similar. For your specific use case though, in the long run you may be much happier using something like [dask-gateway](https://jcrist.github.io/dask-gateway/) to manage your user's dask clusters. This could be stood up on EMR as part of the bootstrap script, and only needs 2 ports exposed for users to create clusters and connect.

**Comment by bschreck** [comment]
Yeah that seems perfect for our use case. I see it just got started this summer. I'll probably have time to switch over to that in a month or so.  But in the meantime I'd really like to have this port option so we can turn this on in production in the meantime.

**Comment by bschreck** [comment]
@jcrist any update on this?

**Comment by jcrist** [comment]
No, I'll likely have time to work on this later this week. If you really need things sooner, feel free to submit a PR. I'd go with `scheduler_port` for the kwarg name, mirroring that of other cluster managers.
